name: Setup Swift v6.0
description: Setup a Swift 6.0 environment on Ubuntu or macOS 
author: Frederik Wallner, Jay Herron, Arindam Karmakar
inputs:
  swift-version: 
    description: Swift version to configure
    required: true
    default: '6.0.0'
outputs:
  version:
    description: The full Swift version that was configured
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'command'  
  color: 'orange'
